#!/bin/bash

function vpn_connected () {
    while read -r line
    do
        if [[ "$line" == "0.0.0.0/1"*"dev tun"* ]]; then
            true
            return
        fi
    done < <(ip route)
    false
    return
}

echo -n "VPN is "
if ! vpn_connected; then
    echo -n "not "
fi
echo connected

vpn_connected
