#!/bin/bash

function vpn_connected () {
    while read -r line
    do
        if [[ "$line" == "0.0.0.0/1"*"dev tun"* ]]; then
            true
            return
        fi
    done < <(ip route)
    false
    return
}
RED='\033[0;31m'
GREEN='\033[0;32m'
NORMAL='\033[0m'
if [ "$1" != "-q" ]; then
    echo -n "VPN is "
    if ! vpn_connected; then
        echo -ne "${RED}"
        echo -n "not "
    else
        echo -ne "${GREEN}"
    fi
    echo -e "connected${NORMAL}"
fi

# Exit status of script allows this to be used elsewhere
vpn_connected
